Traceback (most recent call last):
  File "/home/ywatanabe/proj/entrance/mngs/dsp/_demo_sig.py", line 232, in <module>
    ax.plot(tt, xx[i_batch, i_ch], label=sig_type)
  File "/home/ywatanabe/proj/mngs/src/mngs/plt/_subplots.py", line 176, in wrapper
    result = original_attr(*args, **kwargs)
  File "/home/ywatanabe/proj/mngs/src/mngs/dsp/env/lib64/python3.9/site-packages/matplotlib/axes/_axes.py", line 1724, in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]
  File "/home/ywatanabe/proj/mngs/src/mngs/dsp/env/lib64/python3.9/site-packages/matplotlib/axes/_base.py", line 303, in __call__
    yield from self._plot_args(
  File "/home/ywatanabe/proj/mngs/src/mngs/dsp/env/lib64/python3.9/site-packages/matplotlib/axes/_base.py", line 499, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (2048,) and (20, 2048)
